services:
  BK2K\Syntax\EventListener\RteConfigEnhancer:
    tags:
      - name: event.listener
        identifier: 'ext-syntax/rteConfigEnhancer'
        method: 'beforePrepareConfiguration'
        event: TYPO3\CMS\RteCKEditor\Form\Element\Event\BeforePrepareConfigurationForEditorEvent
