name: CI

on: [push, pull_request]

jobs:
  build-php:
    name: Build PHP
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2']
    steps:
      - id: checkout
        name: Checkout Code
        uses: actions/checkout@v3
      - id: setup_php
        name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
      - id: install
        name: Install
        run: |
          composer install --no-progress
      - id: lint
        name: Lint
        if: ${{ always() && steps.install.conclusion == 'success' }}
        run: |
          composer test:php:lint
      - id: cgl
        name: CGL
        if: ${{ always() && steps.install.conclusion == 'success' }}
        run: |
          composer cgl:ci

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout Code
        uses: actions/checkout@v3
      - id: setup_node
        name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: |
          cd Build
          npm ci
      - name: Build
        run: |
          cd Build
          npm run build
      - name: Status
        run: |
          git status
          git status | grep -q "nothing to commit, working tree clean"
