name: CI

on: [push, pull_request]

jobs:
  build-php:
    name: Build PHP
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        php: ['7.0', '7.1', '7.2', '7.3']
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up PHP ${{ matrix.php }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer:v2
    - name: Update Composer
      run: |
        sudo composer self-update
        composer --version
    - name: Install
      run: |
        composer install --no-progress
    - name: Lint
      run: composer test:php:lint
    - name: CGL
      run: composer cgl

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: |
        cd Build
        yarn install
    - name: Build
      run: |
        cd Build
        yarn build
